"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import "./admin.css";

type AdminUser = { id:number; name:string; email:string; company:string; subscriptionStatus:string; subscriptionExpiresAt:string|null; totalPaidCents:number; isAdmin:boolean; createdAt:string };
type AuditLog = { id:number; category:string; action:string; severity:string; actorEmail:string|null; targetEmail:string|null; resourceType:string; resourceId:string; ipHash:string; metadataJson:string; createdAt:string };
const categoryLabel:Record<string,string>={access:"Acesso",payment:"Pagamento",admin:"Administração",security:"Segurança"};
const actionLabel:Record<string,string>={login_success:"Login realizado",admin_login_success:"Login administrativo",admin_login_challenge:"Verificação administrativa",login_failed:"Falha de login",login_blocked:"Login bloqueado",login_rate_limit_triggered:"Limite de tentativas acionado",login_unverified_email:"E-mail não confirmado",two_factor_failed:"Falha na verificação em duas etapas",two_factor_invalid_challenge:"Desafio de segurança inválido",two_factor_skipped:"Verificação em duas etapas ignorada",admin_access_changed:"Acesso alterado manualmente",admin_revenue_adjusted:"Valor pago ajustado",checkout_created:"Pagamento iniciado",checkout_ready:"Checkout preparado",checkout_failed:"Falha ao iniciar pagamento",payment_approved:"Pagamento aprovado",payment_status_updated:"Status do pagamento atualizado",payment_webhook_invalid_signature:"Assinatura de pagamento inválida",payment_webhook_processing_failed:"Falha interna no pagamento",campaign_admin_denied:"Acesso negado à pesquisa",raffle_admin_denied:"Acesso negado ao sorteio",quiz_admin_denied:"Acesso negado ao GiroQuiz"};
const money=(cents:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(cents/100);
const date=(value:string|null)=>value?new Date(value.includes("T")?value:`${value.replace(" ","T")}Z`).toLocaleDateString("pt-BR"):"—";
const accountAge=(value:string)=>{const created=new Date(value.includes("T")?value:`${value.replace(" ","T")}Z`).getTime(),days=Math.max(0,Math.floor((Date.now()-created)/86_400_000));if(days<1)return"Hoje";if(days<30)return`${days} dia${days===1?"":"s"}`;const months=Math.floor(days/30);if(months<12)return`${months} ${months===1?"mês":"meses"}`;const years=Math.floor(months/12);return`${years} ano${years===1?"":"s"}`};
const accessLabel=(user:AdminUser)=>user.isAdmin?"Administrador":user.subscriptionStatus==="lifetime"?"Vitalício":user.subscriptionStatus==="active"&&user.subscriptionExpiresAt&&Date.parse(user.subscriptionExpiresAt)>Date.now()?`Ativo até ${date(user.subscriptionExpiresAt)}`:"Sem acesso";

export function AdminPage(){
 const[users,setUsers]=useState<AdminUser[]>([]),[logs,setLogs]=useState<AuditLog[]>([]),[suspicious,setSuspicious]=useState(0),[auditCategory,setAuditCategory]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[saving,setSaving]=useState<number|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");const[userResponse,auditResponse]=await Promise.all([fetch("/api/admin/users",{cache:"no-store"}),fetch(`/api/admin/audit?limit=300${auditCategory?`&category=${auditCategory}`:""}`,{cache:"no-store"})]),[userData,auditData]=await Promise.all([userResponse.json(),auditResponse.json()]);if(!userResponse.ok)setError(userData.error||"Não foi possível abrir o painel.");else setUsers(userData.users||[]);if(auditResponse.ok){setLogs(auditData.logs||[]);setSuspicious(auditData.suspiciousLast24Hours||0)}setLoading(false)},[auditCategory]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase("pt-BR");return q?users.filter(user=>`${user.name} ${user.email} ${user.company}`.toLocaleLowerCase("pt-BR").includes(q)):users},[search,users]);
 const revenue=users.reduce((sum,user)=>sum+(user.totalPaidCents||0),0),enabled=users.filter(user=>user.isAdmin||user.subscriptionStatus==="lifetime"||(user.subscriptionStatus==="active"&&!!user.subscriptionExpiresAt&&Date.parse(user.subscriptionExpiresAt)>Date.now())).length;
 const update=async(userId:number,body:{access?:string;totalPaidCents?:number})=>{setSaving(userId);setError("");const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({userId,...body})}),data=await response.json();if(!response.ok)setError(data.error||"Não foi possível salvar.");else await load();setSaving(null)};
 const exportCsv=()=>{const cell=(value:unknown)=>`"${String(value??"").replace(/"/g,'""')}"`,rows=[["Nome","E-mail","Empresa","Cadastro","Tempo de cadastro","Acesso","Vencimento","Total pago"],...filtered.map(user=>[user.name,user.email,user.company,date(user.createdAt),accountAge(user.createdAt),accessLabel(user),date(user.subscriptionExpiresAt),money(user.totalPaidCents||0)])],csv="\uFEFF"+rows.map(row=>row.map(cell).join(";")).join("\r\n"),link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));link.download=`contas-coletivamente-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)};
 const exportAudit=()=>{const cell=(value:unknown)=>`"${String(value??"").replace(/"/g,'""')}"`,rows=[["Data e hora","Categoria","Evento","Gravidade","Responsável","Conta afetada","Recurso","Identificador técnico"],...logs.map(log=>[new Date(log.createdAt.includes("T")?log.createdAt:`${log.createdAt.replace(" ","T")}Z`).toLocaleString("pt-BR"),categoryLabel[log.category]||log.category,actionLabel[log.action]||log.action,log.severity,log.actorEmail||"Sistema",log.targetEmail||"",`${log.resourceType} ${log.resourceId}`.trim(),log.ipHash.slice(0,12)])],csv="\uFEFF"+rows.map(row=>row.map(cell).join(";")).join("\r\n"),link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));link.download=`auditoria-coletivamente-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)};
 if(loading)return <main className="adminCenter"><div className="adminLoader"/></main>;
 if(error&&!users.length)return <main className="adminCenter"><section className="adminDenied"><span>🔒</span><h1>Acesso restrito</h1><p>{error}</p><a href="/">Voltar à página inicial</a></section></main>;
 return <div className="adminShell"><header className="adminNav"><a href="/" className="adminBrand"><i>C</i><span><b>ColetivaMente</b><small>Administração</small></span></a><div><a href="/?modo=conta">Minha conta</a><a href="/">Sair do painel</a></div></header><main className="adminMain">
  <section className="adminHero"><div><p>GESTÃO DA PLATAFORMA</p><h1>Contas e receita</h1><span>Acompanhe clientes, acessos concedidos e o valor acumulado por conta.</span></div><button onClick={exportCsv}>↓ Exportar dados</button></section>
  <section className="adminKpis"><article><small>CONTAS CADASTRADAS</small><strong>{users.length}</strong><span>Total de usuários</span></article><article><small>COM ACESSO</small><strong>{enabled}</strong><span>Ativos, vitalícios e admins</span></article><article><small>RECEITA REGISTRADA</small><strong>{money(revenue)}</strong><span>Valor acumulado</span></article><article className={suspicious?"warning":""}><small>ALERTAS EM 24 HORAS</small><strong>{suspicious}</strong><span>Tentativas suspeitas</span></article></section>
  <section className="adminTableCard"><div className="adminTableHead"><div><h2>Usuários cadastrados</h2><p>{filtered.length} conta{filtered.length===1?"":"s"} encontrada{filtered.length===1?"":"s"}</p></div><input aria-label="Buscar conta" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar nome, e-mail ou empresa"/></div>{error&&<div className="adminAlert">{error}</div>}<div className="adminTableWrap"><table><thead><tr><th>Cliente</th><th>Cadastro</th><th>Acesso</th><th>Valor gerado</th><th>Conceder acesso</th></tr></thead><tbody>{filtered.map(user=><tr key={user.id}><td><div className="adminPerson"><i>{user.name.trim().charAt(0).toUpperCase()}</i><span><b>{user.name}</b><small>{user.email}</small><em>{user.company||"Sem empresa informada"}</em></span></div></td><td><b>{date(user.createdAt)}</b><small>há {accountAge(user.createdAt)}</small></td><td><span className={`adminAccess ${user.isAdmin||user.subscriptionStatus==="lifetime"?"premium":user.subscriptionStatus==="active"?"active":"inactive"}`}>{accessLabel(user)}</span></td><td><div className="adminRevenue"><b>{money(user.totalPaidCents||0)}</b><button disabled={saving===user.id} onClick={()=>{const current=(user.totalPaidCents||0)/100,entered=prompt("Informe o valor total já pago por esta conta (em reais):",current.toFixed(2).replace(".",","));if(entered===null)return;const value=Number(entered.replace(",","."));if(Number.isFinite(value)&&value>=0)update(user.id,{totalPaidCents:Math.round(value*100)})}}>Editar</button></div></td><td><select aria-label={`Conceder acesso para ${user.name}`} defaultValue="" disabled={saving===user.id||user.isAdmin} onChange={event=>{if(event.target.value)update(user.id,{access:event.target.value});event.target.value=""}}><option value="" disabled>{saving===user.id?"Salvando...":user.isAdmin?"Acesso total":"Selecionar"}</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="365">1 ano</option><option value="lifetime">Vitalício</option><option value="revoke">Remover acesso</option></select></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="adminEmpty">Nenhuma conta encontrada.</div>}</section>
  <section className="adminAuditCard"><div className="adminAuditHead"><div><p>TRILHA PROTEGIDA</p><h2>Registro de auditoria</h2><span>Alterações de acesso, pagamentos, ações administrativas e alertas de segurança.</span></div><div><select aria-label="Filtrar auditoria" value={auditCategory} onChange={event=>setAuditCategory(event.target.value)}><option value="">Todos os eventos</option><option value="access">Acessos</option><option value="payment">Pagamentos</option><option value="admin">Administração</option><option value="security">Segurança</option></select><button onClick={exportAudit}>↓ Exportar auditoria</button></div></div><div className="adminAuditList">{logs.map(log=><article key={log.id} className={log.severity}><i/><div><header><b>{actionLabel[log.action]||log.action.replaceAll("_"," ")}</b><span className={log.category}>{categoryLabel[log.category]||log.category}</span></header><p>{log.actorEmail||"Sistema"}{log.targetEmail&&log.targetEmail!==log.actorEmail?` → ${log.targetEmail}`:""}{log.resourceType?` · ${log.resourceType} ${log.resourceId}`:""}</p><small>{new Date(log.createdAt.includes("T")?log.createdAt:`${log.createdAt.replace(" ","T")}Z`).toLocaleString("pt-BR")} · identificação técnica {log.ipHash?log.ipHash.slice(0,12):"não disponível"}</small></div></article>)}{!logs.length&&<div className="adminEmpty">Nenhum evento registrado nesta categoria.</div>}</div></section>
 </main></div>;
}
