"use client";
import { csrfFetch } from "./csrf-client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import "./opinions.css";
import "./hub.css";
import "./voto-gold.css";
import { RaffleBuilder, RaffleView } from "./raffle";
import { Field, LinkBox } from "./ui";
import { AccountPage, AccountStatus, ForgotPasswordPage, LoginPage, RequireActiveSubscription, ResetPasswordPage, SignupPage, VerifyEmailPage } from "./auth";
import { GiroQuizApp } from "./giroquiz";
import { AdminPage } from "./admin";
import { PrivacyPage } from "./privacy";

type Item={id?:number;name:string;category:string;price:string;votes?:number};
type Campaign={title:string;question:string;closed:boolean;feedbackOpen:boolean;hideResults:boolean;offerTitle:string;offerDescription:string;offerUrl:string;offerButton:string;isAdmin:boolean};
type Lead={name:string;email:string;createdAt:string};
type Opinion={category:string;optionId:number;comment:string;voterId:string;createdAt:string;name?:string;email?:string};
const starter:Item[]=[
 {name:"Toyota Hilux",category:"Camionetes",price:"Alto"},{name:"Volkswagen Amarok",category:"Camionetes",price:"Médio"},{name:"Nissan Frontier",category:"Camionetes",price:"Baixo"},
 {name:"iPhone",category:"Celulares",price:"Alto"},{name:"Samsung Galaxy",category:"Celulares",price:"Médio"},{name:"Xiaomi",category:"Celulares",price:"Baixo"},
 {name:"BMW",category:"Carros",price:"Alto"},{name:"Toyota Corolla",category:"Carros",price:"Médio"},{name:"Chevrolet Onix",category:"Carros",price:"Baixo"},
 {name:"Bota premium",category:"Botas",price:"Alto"},{name:"Bota intermediária",category:"Botas",price:"Médio"},{name:"Bota econômica",category:"Botas",price:"Baixo"},
];
const uid=()=>crypto.randomUUID();

export default function Home(){
 const [params,setParams]=useState<{slug:string;raffleSlug:string;legacyAdmin:string;mode:string;token:string}|null>(null);
 useEffect(()=>{const p=new URLSearchParams(location.search),legacyAdmin=p.get("admin")||"";if(legacyAdmin){p.delete("admin");history.replaceState(null,"",`${location.pathname}${p.size?`?${p.toString()}`:""}${location.hash}`)}setParams({slug:p.get("p")||"",raffleSlug:p.get("r")||"",legacyAdmin,mode:p.get("modo")||"",token:p.get("token")||""})},[]);
 if(!params)return <main className="center"><div className="loader"/></main>;
 if(params.raffleSlug)return <RaffleView slug={params.raffleSlug} legacyAdmin={params.legacyAdmin}/>;
 if(!params.slug){
  if(params.mode==="login")return <LoginPage/>;
  if(params.mode==="signup")return <SignupPage/>;
  if(params.mode==="esqueci-senha")return <ForgotPasswordPage/>;
  if(params.mode==="trocar-senha")return <ResetPasswordPage token={params.token}/>;
  if(params.mode==="verificar-email")return <VerifyEmailPage token={params.token}/>;
  if(params.mode==="conta")return <AccountPage/>;
  if(params.mode==="admin")return <AdminPage/>;
  if(params.mode==="privacidade")return <PrivacyPage/>;
  if(params.mode==="voto")return <RequireActiveSubscription><Builder/></RequireActiveSubscription>;
  if(params.mode==="sorteio")return <RequireActiveSubscription><RaffleBuilder/></RequireActiveSubscription>;
  if(params.mode==="quiz")return <GiroQuizApp/>;
  return <><AccountStatus/><ExperienceHub/><a className="hubPrivacyLink" href="/?modo=privacidade">Política de Privacidade</a></>;
 }
 return <CampaignView slug={params.slug} legacyAdmin={params.legacyAdmin}/>;
}

function ExperienceHub(){
 return <main className="hub"><header className="hubNav"><a className="hubBrand" href="/" aria-label="ColetivaMente — página inicial"/><b>Escolha a experiência ideal para o seu momento</b></header><section className="hubHero"><p className="hubEyebrow"><i/> TREINAMENTO, DECISÃO E CELEBRAÇÃO EM UM SÓ LUGAR</p><h1>Treinamentos que a equipe<br/><em>lembra</em> — e recomenda.</h1><p>Capacite, ouça e celebre seu time em dinâmicas ao vivo. Compartilhe o link e acompanhe tudo em tempo real, direto do celular.</p></section><section className="experienceGrid"><a className="experienceCard quizCard" href="/?modo=quiz"><div className="cardTop"><span className="experienceIcon">↻</span><b>TREINAMENTO E ENERGIA</b></div><div><small>01 · APRENDA COMPETINDO</small><h2>GiroQuiz</h2><p>Perguntas, velocidade e pontuação em uma disputa animada que fixa conteúdo em qualquer treinamento.</p></div><ul><li>Ranking em tempo real</li><li>Pontos por acerto e velocidade</li><li>Participação pelo celular</li></ul><strong className="experienceAction">Criar um GiroQuiz <span>→</span></strong><i className="cardOrb"/></a><a className="experienceCard valueCard" href="/?modo=voto"><div className="cardTop"><span className="experienceIcon">✓</span><b>PESQUISA E DECISÃO</b></div><div><small>02 · ESCOLHAS QUE GERAM DADOS</small><h2>Voto em Valor</h2><p>Descubra preferências, apresente resultados e entenda os motivos por trás de cada escolha do time.</p></div><ul><li>Votação por categorias</li><li>Dashboard de resultados</li><li>Segunda rodada de opiniões</li></ul><strong className="experienceAction">Criar uma pesquisa <span>→</span></strong><i className="cardOrb"/></a><a className="experienceCard raffleCard" href="/?modo=sorteio"><div className="cardTop"><span className="experienceIcon">🎉</span><b>CELEBRAÇÃO E DIVERSÃO</b></div><div><small>03 · PARA FECHAR COM CHAVE DE OURO</small><h2>Sorteio</h2><p>Sorteie prêmios entre os participantes e encerre seu evento ou treinamento com um momento leve.</p></div><ul><li>Inscrição pelo celular</li><li>Sorteio ao vivo e animado</li><li>Ideal para fechar treinamentos</li></ul><strong className="experienceAction">Criar um sorteio <span>→</span></strong><i className="cardOrb"/></a></section><footer className="hubFooter"><span>COLETIVAMENTE</span><p>Capacitar · Decidir · Celebrar · Vender</p></footer></main>
}

function Builder(){
 const [title,setTitle]=useState("Escolha que revela valor"); const [question,setQuestion]=useState("Qual destas opções você escolheria?"); const [items,setItems]=useState<Item[]>(starter);
 const [offerTitle,setOfferTitle]=useState("Quer vender mais pelo valor e não pelo preço?"); const [offerDescription,setOfferDescription]=useState("Conheça nossa solução e transforme esta dinâmica em resultados para sua equipe."); const [offerUrl,setOfferUrl]=useState(""); const [offerButton,setOfferButton]=useState("Quero conhecer"); const [hide,setHide]=useState(true); const [busy,setBusy]=useState(false); const [created,setCreated]=useState<{slug:string}|null>(null); const [error,setError]=useState("");
 const categories=[...new Set(items.map(i=>i.category).filter(Boolean))];
 const update=(i:number,k:keyof Item,v:string)=>setItems(a=>a.map((x,n)=>n===i?{...x,[k]:v}:x));
 const renameCategory=(oldName:string,newName:string)=>setItems(a=>a.map(x=>x.category===oldName?{...x,category:newName}:x));
 const addCategory=()=>{if(items.length>17)return;let n=categories.length+1,name=`Nova categoria ${n}`;while(categories.includes(name)){n++;name=`Nova categoria ${n}`}setItems(a=>[...a,{name:"Opção premium",category:name,price:"Alto"},{name:"Opção intermediária",category:name,price:"Médio"},{name:"Opção econômica",category:name,price:"Baixo"}])};
 const create=async()=>{setBusy(true);setError("");try{const r=await csrfFetch("/api/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,question,options:items,offerTitle,offerDescription,offerUrl,offerButton,hideResults:hide})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível criar a votação.");setCreated(d)}catch(e){setError(e instanceof Error?e.message:"Não foi possível criar a votação.")}finally{setBusy(false)}};
 const base=typeof location!=="undefined"?location.origin+location.pathname:"";
 if(created){const vote=`${base}?p=${created.slug}`;return <main className="center"><section className="success"><div className="successIcon">✓</div><p className="eyebrow">CAMPANHA PUBLICADA</p><h1>Seu link está pronto</h1><p>Compartilhe este link com os participantes. Quando você estiver conectado à sua conta, o mesmo endereço abre automaticamente o painel administrativo.</p><LinkBox label="Link da votação" value={vote}/><div className="successActions"><a className="btn primary" href={vote}>Abrir meu painel</a><a className="btn secondary" href={vote}>Ver link compartilhável</a></div></section></main>}
 return <><Header/><main className="container"><div className="hero"><p className="eyebrow">CRIE • COMPARTILHE • CONVERTA</p><h1>Uma votação que abre<br/>a conversa para sua oferta.</h1><p>Monte a dinâmica, envie o link aos celulares e apresente seu produto logo após o voto.</p></div>{error&&<div className="alert">{error}</div>}<section className="panel"><Section n="01" title="Identidade da campanha" desc="O que os participantes verão ao abrir o link."/><div className="formGrid"><Field label="Nome da campanha"><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Pergunta principal"><input value={question} onChange={e=>setQuestion(e.target.value)}/></Field></div></section>
 <section className="categoriesSection"><div className="categoriesHeading"><Section n="02" title="Categorias da dinâmica" desc="Cada quadro representa uma escolha diferente para o participante."/><button className="btn secondary" disabled={items.length>17} onClick={addCategory}>＋ Adicionar categoria</button></div>{categories.map((category,categoryIndex)=>{const categoryItems=items.map((item,index)=>({item,index})).filter(x=>x.item.category===category);return <section className="panel categoryPanel" key={categoryIndex}><div className="categoryEditorHead"><div><span className="categoryCount">CATEGORIA {String(categoryIndex+1).padStart(2,"0")}</span><input className="categoryName" value={category} onChange={e=>renameCategory(category,e.target.value)} aria-label="Nome da categoria"/></div><div className="categoryButtons"><button className="btn secondary" disabled={items.length>=20} onClick={()=>setItems(a=>[...a,{name:"",category,price:"Médio"}])}>＋ Adicionar opção</button><button className="btn textDanger" disabled={categories.length<=1} onClick={()=>setItems(a=>a.filter(x=>x.category!==category))}>Remover quadro</button></div></div><div className="optionList">{categoryItems.map(({item,index},localIndex)=><div className="optionEdit grouped" key={index}><span className="num">{String(localIndex+1).padStart(2,"0")}</span><Field label="Nome da opção"><input value={item.name} onChange={e=>update(index,"name",e.target.value)}/></Field><Field label="Preço"><select value={item.price} onChange={e=>update(index,"price",e.target.value)}><option>Alto</option><option>Médio</option><option>Baixo</option></select></Field><button className="remove" disabled={categoryItems.length<=1||items.length<=3} onClick={()=>setItems(a=>a.filter((_,n)=>n!==index))}>×</button></div>)}</div></section>})}</section>
 <section className="panel"><Section n="03" title="Sua oferta após o voto" desc="Transforme a participação em uma oportunidade comercial."/><div className="formGrid"><Field label="Título da oferta"><input value={offerTitle} onChange={e=>setOfferTitle(e.target.value)}/></Field><Field label="Texto curto"><textarea value={offerDescription} onChange={e=>setOfferDescription(e.target.value)}/></Field><Field label="Link do produto, WhatsApp ou checkout"><input type="url" placeholder="https://..." value={offerUrl} onChange={e=>setOfferUrl(e.target.value)}/></Field><Field label="Texto do botão"><input value={offerButton} onChange={e=>setOfferButton(e.target.value)}/></Field></div></section>
 {error&&<div className="alert launchError" role="alert">{error}</div>}<section className="launch"><label><input type="checkbox" checked={hide} onChange={e=>setHide(e.target.checked)}/><span><strong>Ocultar resultados enquanto a votação estiver aberta</strong><small>Ajuda a evitar influência entre os participantes.</small></span></label><button className="btn primary big" disabled={busy} onClick={create}>{busy?"Criando campanha...":"Criar link de votação →"}</button></section></main><Footer/></>;
}

function CampaignView({slug,legacyAdmin}:{slug:string;legacyAdmin:string}){
 const legacyClaimed=useRef(false);
 const [campaign,setCampaign]=useState<Campaign|null>(null),[items,setItems]=useState<Item[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<Record<string,number>>({}),[voted,setVoted]=useState(false),[error,setError]=useState("");
 const [started,setStarted]=useState(false),[name,setName]=useState(""),[email,setEmail]=useState(""),[consent,setConsent]=useState(false),[leads,setLeads]=useState<Lead[]>([]),[opinions,setOpinions]=useState<Opinion[]>([]),[feedbackDone,setFeedbackDone]=useState(false),[linkCopied,setLinkCopied]=useState(false);
 const load=useCallback(async()=>{if(legacyAdmin&&!legacyClaimed.current){legacyClaimed.current=true;await fetch(`/api/campaigns/${encodeURIComponent(slug)}/claim`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({legacyToken:legacyAdmin})})}const r=await fetch(`/api/campaigns/${encodeURIComponent(slug)}`,{cache:"no-store"});const d=await r.json();if(r.ok){setCampaign(d.campaign);setItems(d.options);setTotal(d.total||0);setLeads(d.participants||[]);setOpinions(d.feedback||[])}else setError(d.error)},[slug,legacyAdmin]);
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[load]);
 useEffect(()=>{setVoted(localStorage.getItem(`voted-${slug}`)==="1");setFeedbackDone(localStorage.getItem(`feedback-${slug}`)==="1")},[slug]);
 const submit=async()=>{if(Object.keys(selected).length!==grouped.length)return;let voter=localStorage.getItem("voter-id");if(!voter){voter=uid();localStorage.setItem("voter-id",voter)}const r=await fetch(`/api/campaigns/${slug}/vote`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({selections:Object.values(selected),voterId:voter,name,email,consent})});const d=await r.json();if(r.ok){localStorage.setItem(`voted-${slug}`,"1");setVoted(true);load()}else setError(d.error)};
 const action=async(a:string)=>{const r=await fetch(`/api/campaigns/${slug}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:a})});if(!r.ok)return;setCampaign(current=>current?{...current,closed:a==="close"?true:a==="reopen"?false:current.closed,feedbackOpen:a==="feedback"?true:a==="close"||a==="endFeedback"?false:current.feedbackOpen}:current);setTimeout(load,300)};
 const share=()=>navigator.share?navigator.share({title:campaign?.title,url:location.href}):navigator.clipboard.writeText(location.href);
 const copyVoteLink=async()=>{const url=`${location.origin}${location.pathname}?p=${encodeURIComponent(slug)}`;await navigator.clipboard.writeText(url);setLinkCopied(true);setTimeout(()=>setLinkCopied(false),2200)};
 const grouped=useMemo(()=>[...new Set(items.map(i=>i.category))].map(category=>({category,items:items.filter(i=>i.category===category)})),[items]);
 if(error&&!campaign)return <main className="center"><section className="success"><h1>Não foi possível abrir</h1><p>{error}</p></section></main>;if(!campaign)return <main className="center"><div className="loader"/></main>;
 if(campaign.isAdmin&&campaign.closed)return <AdminDashboard campaign={campaign} items={items} total={total} participants={leads.length} opinions={opinions} onAction={action} onShare={share}/>;
 if(!campaign.isAdmin&&campaign.closed&&campaign.feedbackOpen&&voted&&!feedbackDone)return <FeedbackRound slug={slug} campaign={campaign} items={items} onDone={()=>setFeedbackDone(true)}/>;
 if(!campaign.isAdmin&&campaign.closed&&feedbackDone)return <><Header title={campaign.title}/><main className="center"><section className="success"><div className="successIcon">✓</div><p className="eyebrow">OPINIÕES ENVIADAS</p><h1>Obrigado pela sua contribuição!</h1><p>Suas respostas foram registradas. A segunda rodada continua aberta para os outros participantes e só será encerrada pelo organizador.</p></section></main><Footer/></>;
 if(voted&&!campaign.isAdmin)return <><Header title={campaign.title}/><main className="center"><section className="success"><div className="successIcon">✓</div><p className="eyebrow">VOTO REGISTRADO</p><h1>Obrigado por participar!</h1><p>Sua escolha já entrou no resultado.</p>{campaign.offerTitle&&<div className="offer"><span>PRÓXIMO PASSO</span><h2>{campaign.offerTitle}</h2><p>{campaign.offerDescription}</p>{campaign.offerUrl&&<a className="btn primary big" href={campaign.offerUrl} target="_blank" rel="noreferrer">{campaign.offerButton} →</a>}</div>}{(!campaign.hideResults||campaign.closed)&&<Results items={items} total={total}/>}</section></main></>;
 if(campaign.closed&&!campaign.isAdmin)return <><Header title={campaign.title}/><main className="container campaign"><div className="finalHead"><p className="eyebrow">VOTAÇÃO ENCERRADA</p><h1>Resultado final</h1><p>Confira as escolhas dos participantes em cada categoria.</p></div><Results items={items} total={total}/></main><Footer/></>;
 if(!campaign.isAdmin&&!started)return <><Header title={campaign.title}/><main className="center"><section className="identityCard"><p className="eyebrow">ANTES DE COMEÇAR</p><h1>Conte-nos quem é você</h1><p>Preencha seus dados para acessar a votação.</p>{error&&<div className="alert">{error}</div>}<div className="identityFields"><Field label="Seu nome completo"><input autoFocus autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: João da Silva"/></Field><Field label="Seu melhor e-mail"><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com"/></Field></div><label className="privacyConsent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Concordo com a <a href="/?modo=privacidade" target="_blank">Política de Privacidade</a> e autorizo o uso dos dados para esta dinâmica.</span></label><button className="btn primary big" disabled={!consent||name.trim().length<3||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)} onClick={()=>{setError("");setStarted(true)}}>Continuar para a votação →</button><small className="privacy">🔒 Seus dados serão enviados ao organizador desta dinâmica e não aparecerão publicamente.</small></section></main><Footer/></>;
 return <><Header title={campaign.title}/><main className="container campaign"><div className="campaignHead"><div><p className="status">● {campaign.closed?"VOTAÇÃO ENCERRADA":"VOTAÇÃO ABERTA"}</p><h1>{campaign.question}</h1><p>{campaign.isAdmin?`${total} votos recebidos · atualização automática`:"Escolha uma alternativa e confirme seu voto."}</p></div><div className="campaignShareActions"><button className="btn copySurvey" onClick={copyVoteLink}>{linkCopied?"✓ Link copiado!":"⧉ Copiar link da pesquisa"}</button><button className="btn secondary" onClick={share}>↗ Compartilhar</button></div></div>
 {campaign.isAdmin?<><Results items={items} total={total}/><div className="adminBar"><div><strong>Painel do organizador</strong><small>Este endereço é privado. Não envie o link administrativo.</small></div><div>{campaign.closed?<button className="btn secondary" onClick={()=>action("reopen")}>Reabrir votação</button>:<button className="btn danger" onClick={()=>action("close")}>■ Encerrar votação</button>} <button className="btn danger" onClick={()=>action("reset")}>↻ Zerar votos</button></div></div></>:campaign.closed?<section className="success"><h2>Esta votação foi encerrada</h2>{!campaign.hideResults&&<Results items={items} total={total}/>}</section>:<><div className="categoryGroups">{grouped.map(g=><section key={g.category}><div className="categoryTitle"><span>{g.category}</span><i>Escolha 1 de {g.items.length}</i></div><div className="voteGrid">{g.items.map(item=><button className={`voteCard ${selected[g.category]===item.id?"selected":""}`} onClick={()=>setSelected(s=>({...s,[g.category]:item.id!}))} key={item.id}><span className={`price ${item.price}`}>PREÇO {item.price.toUpperCase()}</span><strong>{item.name}</strong><small>{item.category}</small><b>{selected[g.category]===item.id?"✓":""}</b></button>)}</div></section>)}</div>{error&&<div className="alert">{error}</div>}<div className="confirmBar"><span>{Object.keys(selected).length} de {grouped.length} categorias respondidas</span><button className="btn primary big" disabled={Object.keys(selected).length!==grouped.length} onClick={submit}>Confirmar minhas escolhas →</button></div></>}</main><Footer/></>;
}

function AdminDashboard({campaign,items,total,participants,opinions,onAction,onShare}:{campaign:Campaign;items:Item[];total:number;participants:number;opinions:Opinion[];onAction:(a:string)=>void;onShare:()=>void}){
 const [showOpinions,setShowOpinions]=useState(false);
 const categories=[...new Set(items.map(i=>i.category))];
 const winners=categories.map(category=>items.filter(i=>i.category===category).sort((a,b)=>(b.votes||0)-(a.votes||0))[0]).filter(Boolean);
 return <div className="dashboard"><header className="dashNav"><div className="brand"><span>V</span><div><strong>Painel de resultados</strong><small>{campaign.title}</small></div></div><div><button className="btn dashGhost" onClick={onShare}>↗ Compartilhar</button><button className="btn dashGhost" onClick={()=>document.documentElement.requestFullscreen?.()}>⛶ Tela cheia</button></div></header><main className="dashMain"><div className="dashHero"><div><p className="dashLive"><i/> VOTAÇÃO ENCERRADA</p><h1>Resultado final</h1><p>{campaign.question}</p></div><button className="btn reopen" onClick={()=>onAction("reopen")}>↻ Reabrir votação</button></div><section className="kpis"><article><span>PARTICIPANTES</span><strong>{participants||Math.round(total/Math.max(categories.length,1))}</strong><small>Pessoas que responderam</small></article><article><span>ESCOLHAS</span><strong>{total}</strong><small>Votos em todas as categorias</small></article><article><span>CATEGORIAS</span><strong>{categories.length}</strong><small>Quadros avaliados</small></article><article className="winnerKpi"><span>DESTAQUES</span><strong>{winners.length}</strong><small>Vencedores definidos</small></article></section><div className="dashGrid">{categories.map((category,catIndex)=>{const group=items.filter(i=>i.category===category).sort((a,b)=>(b.votes||0)-(a.votes||0)),sum=group.reduce((n,i)=>n+(i.votes||0),0);return <section className="dashCard" key={category}><div className="dashCardHead"><span className="dashIcon">{["▰","▣","◆","◒"][catIndex%4]}</span><div><small>CATEGORIA {String(catIndex+1).padStart(2,"0")}</small><h2>{category}</h2></div><b>{sum} votos</b></div>{group.map((item,i)=>{const p=sum?Math.round((item.votes||0)/sum*100):0;return <div className={`dashResult ${i===0&&sum?"champion":""}`} key={item.id}><div className="dashResultTop"><span className="dashRank">{i===0&&sum?"★":i+1}</span><span><strong>{item.name}</strong></span><span><strong>{p}%</strong><small>{item.votes||0} votos</small></span></div><div className="dashBar"><i style={{width:`${p}%`}}/></div></div>})}</section>})}</div><div className="dashFooter"><span>Os votos da 1ª rodada permanecem salvos</span><div className="feedbackActions">{campaign.feedbackOpen?<button className="btn endFeedback" onClick={()=>onAction("endFeedback")}>Encerrar 2ª rodada</button>:opinions.length>0?<button className="btn feedbackActive" disabled>✓ 2ª rodada encerrada</button>:<button className="btn startFeedback" onClick={()=>onAction("feedback")}>Iniciar 2ª rodada →</button>}<button className="btn viewOpinions" onClick={()=>setShowOpinions(true)}>Ver opiniões ({opinions.length})</button><a className="btn homeButton" href="/">⌂ Voltar à página inicial</a></div></div></main>{showOpinions&&<OpinionsModal opinions={opinions} items={items} onClose={()=>setShowOpinions(false)}/>}</div>
}

function OpinionsModal({opinions,items,onClose}:{opinions:Opinion[];items:Item[];onClose:()=>void}){
 const categories=[...new Set(opinions.map(opinion=>opinion.category))];
 return <div className="opinionsOverlay" role="dialog" aria-modal="true" aria-label="Opiniões da segunda rodada" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="opinionsModal"><header><div><p className="eyebrow">SEGUNDA RODADA</p><h2>Opiniões por categoria</h2><p>{opinions.length} respostas anônimas recebidas</p></div><button className="closeOpinions" onClick={onClose} aria-label="Fechar">×</button></header>{opinions.length===0?<div className="emptyOpinions"><strong>Ainda não há opiniões.</strong><p>Assim que os participantes enviarem suas respostas, elas aparecerão aqui automaticamente.</p></div>:<div className="opinionGroups">{categories.map((category,index)=>{const group=opinions.filter(opinion=>opinion.category===category),winner=items.find(item=>item.id===group[0]?.optionId);return <section className="opinionGroup" key={category}><div className="opinionGroupHead"><span>{String(index+1).padStart(2,"0")}</span><div><small>{category}</small><h3>{winner?.name||"Produto vencedor"}</h3></div><b>{group.length} opiniões</b></div><div className="groupComments">{group.map((opinion,opinionIndex)=><p key={`${opinion.voterId}-${opinionIndex}`}>“{opinion.comment}”</p>)}</div></section>})}</div>}</section></div>
}

function Results({items,total}:{items:Item[];total:number}){const categories=[...new Set(items.map(i=>i.category))];return <section className="results"><div className="resultsTitle"><h2>Resultados por categoria</h2><span>{total} escolhas registradas</span></div>{categories.map(category=>{const categoryItems=items.filter(i=>i.category===category).sort((a,b)=>(b.votes||0)-(a.votes||0)),categoryTotal=categoryItems.reduce((n,i)=>n+(i.votes||0),0);return <div className="resultGroup" key={category}><h3>{category}<small>{categoryTotal} participantes</small></h3>{categoryItems.map((item,i)=>{const p=categoryTotal?Math.round((item.votes||0)/categoryTotal*100):0;return <div className={`result ${i===0&&categoryTotal?"winner":""}`} key={item.id}><span className="rank">{i+1}</span><div><div className="resultLabel"><span><strong>{item.name}</strong><small>Preço {item.price.toLowerCase()}</small></span><span><strong>{p}%</strong><small>{item.votes||0} votos</small></span></div><div className="bar"><i style={{width:`${p}%`}}/></div></div></div>})}</div>})}</section>}
function Header({title="Voto em Valor"}:{title?:string}){return <header><a className="brand" href="/"><span>V</span><div><strong>{title}</strong><small>ESCOLHAS QUE REVELAM VALOR</small></div></a></header>}
function Footer(){return <footer>Voto em Valor · Dinâmicas comerciais que geram conversa · <a href="/?modo=privacidade">Privacidade</a></footer>}
function Section({n,title,desc}:{n:string;title:string;desc:string}){return <div className="sectionTitle"><span>{n}</span><div><h2>{title}</h2><p>{desc}</p></div></div>}

function FeedbackRound({slug,campaign,items,onDone}:{slug:string;campaign:Campaign;items:Item[];onDone:()=>void}){
 const categories=[...new Set(items.map(i=>i.category))];
 const winners=categories.map(category=>items.filter(i=>i.category===category).sort((a,b)=>(b.votes||0)-(a.votes||0))[0]).filter(Boolean);
 const [answers,setAnswers]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const complete=winners.length>0&&winners.every(w=>(answers[w.category]||"").trim().length>=5);
 const send=async()=>{setBusy(true);setError("");const voterId=localStorage.getItem("voter-id")||"";const r=await fetch(`/api/campaigns/${slug}/feedback`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({voterId,opinions:winners.map(w=>({category:w.category,optionId:w.id,comment:answers[w.category]}))})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);localStorage.setItem(`feedback-${slug}`,"1");onDone()};
 return <><Header title={campaign.title}/><main className="feedbackPage"><div className="feedbackIntro"><p className="eyebrow">SEGUNDA RODADA</p><h1>Por que eles ganharam?</h1><p>Explique brevemente o que fez cada produto ser o mais escolhido.</p></div>{error&&<div className="alert">{error}</div>}<div className="feedbackGrid">{winners.map((winner,index)=><section className="feedbackCard" key={winner.id}><span className="feedbackNumber">{String(index+1).padStart(2,"0")}</span><small>{winner.category}</small><h2>{winner.name}</h2><label>Por que foi a melhor escolha?</label><textarea maxLength={300} value={answers[winner.category]||""} onChange={e=>setAnswers(a=>({...a,[winner.category]:e.target.value}))} placeholder={`Ex.: A ${winner.name} transmite mais confiança porque...`}/><i>{(answers[winner.category]||"").length}/300</i></section>)}</div><div className="feedbackSubmit"><span>{Object.values(answers).filter(a=>a.trim().length>=5).length} de {winners.length} respostas preenchidas</span><button className="btn primary big" disabled={!complete||busy} onClick={send}>{busy?"Enviando...":"Enviar minhas opiniões →"}</button></div></main><Footer/></>;
}
