"use client";
import "./privacy.css";

export function PrivacyPage() {
  return <main className="privacyPage"><header><a href="/">← Voltar</a><strong>ColetivaMente</strong></header><article>
    <p className="privacyTag">TRANSPARÊNCIA E PROTEÇÃO DE DADOS</p><h1>Política de Privacidade</h1><p className="privacyDate">Última atualização: 26 de julho de 2026</p>
    <section><h2>1. Quem somos</h2><p>A ColetivaMente oferece ferramentas para treinamentos, votações, pesquisas e sorteios. Quando uma empresa ou organizador cria uma dinâmica, esse organizador define a finalidade da coleta e atua como controlador dos dados dos participantes. A ColetivaMente processa esses dados para viabilizar a dinâmica e prestar o serviço.</p><p>Ao cadastrar manualmente dados de participantes, o organizador declara possuir autorização ou outra base legal adequada para realizar esse tratamento.</p></section>
    <section><h2>2. Dados coletados</h2><p>Podemos coletar nome, e-mail, empresa, informações da conta, respostas, votos, opiniões, pontuações, registros de participação, consentimento, pagamentos e informações técnicas essenciais de segurança, como endereço IP e data e hora de acesso.</p></section>
    <section><h2>3. Para que usamos</h2><ul><li>Criar e proteger contas;</li><li>Permitir a participação em GiroQuiz, pesquisas e sorteios;</li><li>Apresentar resultados ao organizador da dinâmica;</li><li>Processar pagamentos e liberar acesso;</li><li>Prevenir fraude, abuso e acessos indevidos;</li><li>Enviar confirmações de e-mail e recuperação de senha.</li></ul><p>Não vendemos listas de nomes ou e-mails e não usamos os dados dos participantes para publicidade própria sem autorização específica.</p></section>
    <section><h2>4. Compartilhamento</h2><p>Os dados podem ser disponibilizados ao organizador responsável pela dinâmica e a fornecedores necessários à operação, como Cloudflare, Resend e Mercado Pago, sempre limitados à finalidade do serviço. Também poderemos fornecer informações quando houver obrigação legal.</p></section>
    <section><h2>5. Armazenamento e segurança</h2><p>Aplicamos controles de acesso, sessões protegidas, limitação de tentativas, proteção contra requisições falsas, autenticação em duas etapas opcional e armazenamento restrito. Nenhum sistema é absolutamente invulnerável, mas adotamos medidas razoáveis para reduzir riscos.</p></section>
    <section><h2>6. Prazo de conservação</h2><p>Os dados são mantidos enquanto a conta ou dinâmica estiver ativa e pelo tempo necessário para cumprir obrigações legais, resolver disputas e preservar registros de segurança. Dados sem necessidade operacional ou legal poderão ser excluídos ou anonimizados.</p></section>
    <section><h2>7. Seus direitos</h2><p>Você pode solicitar confirmação do tratamento, acesso, correção, informação sobre compartilhamento, revogação do consentimento e, quando aplicável, exclusão, bloqueio, anonimização ou portabilidade. A retirada do consentimento poderá impedir a participação na dinâmica quando nome e e-mail forem necessários para seu funcionamento.</p></section>
    <section><h2>8. Solicitações</h2><p>Para exercer seus direitos, escreva para <a href="mailto:elvispieta@hotmail.com">elvispieta@hotmail.com</a>, informando o e-mail usado no serviço e a solicitação. Poderemos pedir confirmação de identidade antes de entregar, corrigir ou excluir dados.</p></section>
    <section><h2>9. Alterações</h2><p>Esta política poderá ser atualizada para refletir mudanças no serviço ou na legislação. A data da versão mais recente ficará indicada no início desta página.</p></section>
    <aside>Ao marcar a caixa de consentimento, você declara que leu esta política e compreendeu como os dados serão tratados para a finalidade informada.</aside>
  </article></main>;
}
